import { useMemo, useRef, useState } from "react";
import { useAutomationAuditReviews } from "../../hooks/useAutomationAuditReviews";

type Props = { serverId: string | null; serverName?: string | null; currentRole: string | null };
const canCreateFor = (role: string | null) => Boolean(role && ["OWNER","ADMIN","MODERATOR","ARCHITECT","DEVELOPER","OPERATOR"].includes(role));
const canReviewFor = (role: string | null) => Boolean(role && ["OWNER","ADMIN","MODERATOR","OPERATOR"].includes(role));

export function AutomationAuditReviewRoom({ serverId, serverName, currentRole }: Props) {
  const api = useAutomationAuditReviews(serverId ?? ""); const fileRef = useRef<HTMLInputElement>(null); const [selectedId, setSelectedId] = useState(""); const [note, setNote] = useState(""); const [localError, setLocalError] = useState(""); const [checks, setChecks] = useState({ scopeConfirmed: false, claimsConfirmed: false, noExternalActionsConfirmed: false });
  const selected = useMemo(() => api.reviews.find((item) => item.id === selectedId) ?? api.reviews[0], [api.reviews, selectedId]); const canCreate = canCreateFor(currentRole); const canReview = canReviewFor(currentRole); const allChecked = Object.values(checks).every(Boolean);
  const handleFile = async (file?: File) => { if (!file) return; if (!file.name.toLowerCase().endsWith(".json")) { setLocalError("Выберите eclipse.automation-audit.v1 JSON."); return; } try { const artifact = JSON.parse(await file.text()) as unknown; const review = await api.importArtifact(artifact); if (review) { setSelectedId(review.id); setLocalError(""); } } catch { setLocalError("Файл не является корректным JSON."); } finally { if (fileRef.current) fileRef.current.value = ""; } };
  const decide = async (decision: "APPROVE" | "REJECT") => { if (!selected) return; const review = await api.decide(selected, decision, note, checks); if (review) { setSelectedId(review.id); setNote(""); } };
  return <main className="ec-agent-office" aria-labelledby="audit-room-title">
    <header className="ec-agent-office__header"><div className="ec-agent-office__identity"><span className="ec-agent-office__mark">A</span><div><p className="ec-agent-office__eyebrow">{serverName ?? "Eclipse Forge"} · Agent Office</p><h1 id="audit-room-title">Automation Audit Review</h1><p>Проверьте read-only карту, evidence, claims и pilot proposal. Approval не выполняет внешние действия.</p></div></div><div className="ec-agent-office__run-meta"><span className="ec-agent-office__contract">eclipse.automation-audit.v1</span><button className="ec-btn ec-btn--primary" type="button" disabled={!canCreate || api.busy} onClick={() => fileRef.current?.click()}>{api.busy ? "Обрабатываем…" : "Импорт Audit JSON"}</button><input ref={fileRef} className="ec-growth-file-input" type="file" accept="application/json,.json" aria-label="Выбрать Automation Audit JSON" onChange={(event) => void handleFile(event.target.files?.[0])}/></div></header>
    {(api.error || localError) && <div className="ec-growth-error" role="alert">{localError || api.error}</div>}
    {api.loading ? <section className="ec-growth-loading" aria-label="Загрузка audits"><span/><span/><span/></section> : !selected ? <section className="ec-growth-empty"><span className="ec-agent-office__mark">A</span><h2>Очередь audit пуста</h2><p>Подготовьте и утвердите read-only audit в AI Hub, затем импортируйте JSON для независимого review.</p><button className="ec-btn ec-btn--primary" type="button" disabled={!canCreate} onClick={() => fileRef.current?.click()}>Импортировать JSON</button></section> : <div className="ec-deck-workspace">
      <section className="ec-deck-canvas"><div className="ec-growth-list">{api.reviews.map((review) => <button type="button" key={review.id} data-selected={review.id === selected.id} onClick={() => setSelectedId(review.id)}><span>{review.artifact.input.businessName}</span><small>{review.artifact.input.processName} · {review.reviewStatus}</small></button>)}</div><article className="ec-growth-artifact"><p className="ec-agent-office__section-label">Read-only process map</p><h2>{selected.artifact.input.objective}</h2><ol>{selected.artifact.processMap.map((step) => <li key={step.order}><strong>{step.order}. {step.step}</strong> · {step.system ?? "система не назначена"}</li>)}</ol><p className="ec-agent-office__section-label">SaaS validation</p><dl className="ec-growth-provenance"><div><dt>Problem</dt><dd>{selected.artifact.input.validation.problem}</dd></div><div><dt>Audience</dt><dd>{selected.artifact.input.validation.audience}</dd></div><div><dt>Offer</dt><dd>{selected.artifact.input.validation.offer}</dd></div><div><dt>Evidence</dt><dd>{selected.artifact.input.validation.interviews} interviews · {selected.artifact.input.validation.waitlist} waitlist</dd></div></dl><p className="ec-agent-office__section-label">Claim Auditor</p>{selected.artifact.claimAudit.map((claim) => <blockquote key={claim.claim} data-status={claim.status}><strong>{claim.status}</strong> · {claim.claim}<small>{claim.reason}</small></blockquote>)}</article></section>
      <aside className="ec-deck-review"><section data-status={selected.reviewStatus}><p className="ec-agent-office__section-label">Human gate · v{selected.version}</p><h2>{selected.reviewStatus === "PENDING" ? "Требуется решение" : selected.reviewStatus === "APPROVED" ? "Audit принят" : "Нужна доработка"}</h2>{selected.reviewStatus === "PENDING" ? canReview ? <><p>Решение подтверждает только proposal и evidence.</p>{([['scopeConfirmed','Scope и exclusions проверены'],['claimsConfirmed','Claims и evidence проверены'],['noExternalActionsConfirmed','OAuth, отправки, платежи и production запрещены']] as const).map(([key,label]) => <label key={key}><input type="checkbox" checked={checks[key]} onChange={(event) => setChecks({ ...checks, [key]: event.target.checked })}/><span>{label}</span></label>)}<textarea value={note} maxLength={1000} placeholder="Комментарий или причина доработки" onChange={(event) => setNote(event.target.value)}/><div><button className="ec-btn ec-btn--primary" type="button" disabled={!allChecked || api.busy} onClick={() => void decide("APPROVE")}>Утвердить read-only pilot</button><button className="ec-btn ec-btn--danger" type="button" disabled={note.trim().length < 3 || api.busy} onClick={() => void decide("REJECT")}>Вернуть на доработку</button></div></> : <p>Решение принимает участник с правом approval.</p> : selected.receipt ? <><p>{selected.receipt.statement}</p><code>{selected.receipt.receiptId}</code></> : <p>{selected.reviewNote}</p>}</section><section><p className="ec-agent-office__section-label">Proposal</p><p>{selected.artifact.input.proposal.outcome}</p><small>{selected.artifact.input.proposal.pilotMetric}</small></section></aside>
    </div>}
  </main>;
}
