import { useEffect, useMemo, useRef, useState } from "react";
import type { MemberRole } from "../../hooks/useMembers";
import { type SpecGateReviewStatus, type SpecGateReviewView, useSpecGateReviews } from "../../hooks/useSpecGateReviews";
import { hasPermission } from "../../lib/memberRoles";

type Props = { serverId: string | null; serverName: string | null; currentRole: MemberRole | null };
const STATUS: Record<SpecGateReviewStatus, string> = { PENDING: "Ждёт проверки", APPROVED: "Спецификация принята", REJECTED: "Нужна доработка" };
const EMPTY = { scopeConfirmed: false, risksConfirmed: false, rollbackConfirmed: false };
function SpecIcon() { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M4 5h10M4 9h10M4 13h6M4 17h6"/><rect x="12" y="12" width="8" height="7" rx="1.5"/><path d="M14 12v-2a2 2 0 0 1 4 0v2"/></svg>; }
const formatDate = (value: string) => new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
function Row({ item, selected, onSelect }: { item: SpecGateReviewView; selected: boolean; onSelect: () => void }) { return <button type="button" className="ec-deck-row" data-selected={selected} data-status={item.reviewStatus} onClick={onSelect}><span aria-hidden/><div><strong>{item.artifact.input.projectName}</strong><small>{item.artifact.input.repository} · {formatDate(item.createdAt)}</small></div><em>{STATUS[item.reviewStatus]}</em></button>; }

export function SpecGateReviewRoom({ serverId, serverName, currentRole }: Props) {
  const api = useSpecGateReviews(serverId, true);
  const fileRef = useRef<HTMLInputElement>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);
  const [note, setNote] = useState("");
  const [checklist, setChecklist] = useState(EMPTY);
  const selected = useMemo(() => api.reviews.find((item) => item.id === selectedId) ?? api.reviews[0] ?? null, [api.reviews, selectedId]);
  const canCreate = currentRole != null && hasPermission(currentRole, "TASK_CREATE");
  const canReview = currentRole != null && hasPermission(currentRole, "TASK_APPROVE");
  const allChecked = checklist.scopeConfirmed && checklist.risksConfirmed && checklist.rollbackConfirmed;
  useEffect(() => { if (!selectedId && api.reviews[0]) setSelectedId(api.reviews[0].id); if (selectedId && !api.reviews.some((item) => item.id === selectedId)) setSelectedId(api.reviews[0]?.id ?? null); }, [api.reviews, selectedId]);
  useEffect(() => { setChecklist(EMPTY); setNote(selected?.reviewNote ?? ""); }, [selected?.id, selected?.reviewNote]);
  const handleFile = async (file?: File) => {
    if (!file) return; setLocalError(null); api.clearError();
    if (file.size > 96 * 1024) { setLocalError("Файл больше безопасного лимита 96 КБ."); return; }
    if (!file.name.toLowerCase().endsWith(".json")) { setLocalError("Выберите eclipse.spec-gate.v1 JSON."); return; }
    try { const imported = await api.importArtifact(JSON.parse(await file.text()) as unknown); if (imported) setSelectedId(imported.id); }
    catch (cause) { setLocalError(cause instanceof SyntaxError ? "Файл не является корректным JSON." : "Не удалось прочитать файл."); }
    finally { if (fileRef.current) fileRef.current.value = ""; }
  };
  const decide = async (decision: "APPROVE" | "REJECT") => { if (!selected) return; const updated = await api.reviewArtifact(selected.id, selected.version, decision, checklist, note); if (updated) setSelectedId(updated.id); };
  if (!serverId) return <main className="ec-agent-office ec-agent-office--centered"><section className="ec-growth-empty"><span className="ec-agent-office__mark"><SpecIcon/></span><h1>Выберите пространство</h1><p>Спецификации хранятся только внутри выбранной команды.</p></section></main>;

  return <main className="ec-agent-office ec-deck-room" aria-labelledby="spec-room-title" aria-busy={api.loading}>
    <header className="ec-agent-office__header"><div className="ec-agent-office__identity"><span className="ec-agent-office__mark"><SpecIcon/></span><div><p className="ec-agent-office__eyebrow">{serverName ?? "Eclipse Forge"} · AI-офис</p><h1 id="spec-room-title">Проверка требований</h1><p>Проверьте объём, критерии, риски и план отката до того, как задача перейдёт в реализацию.</p></div></div><div className="ec-agent-office__run-meta"><span className="ec-agent-office__contract">eclipse.spec-gate.v1</span><span className="ec-agent-office__queue">{api.reviews.filter((item) => item.reviewStatus === "PENDING").length} на проверке</span><button type="button" className="ec-btn ec-btn--primary" disabled={!canCreate || api.importing} onClick={() => fileRef.current?.click()}>{api.importing ? "Импортируем…" : "Импорт JSON-требований"}</button><input ref={fileRef} className="ec-growth-file-input" type="file" accept="application/json,.json" aria-label="Выбрать JSON-требования" onChange={(event) => void handleFile(event.target.files?.[0])}/></div></header>
    <section className="ec-agent-office__safety"><strong>Новая граница доверия</strong><span>Согласование из AI Hub сбрасывается. Даже решение Chat не запускает командную строку, GitHub, зависимости или развёртывание.</span><span className="ec-growth-budget">до {api.policy?.maxPendingReviewsPerOperator ?? 20} в очереди</span></section>
    {(api.error || localError) && <div className="ec-growth-alert" role="alert"><span>{localError ?? api.error}</span><div>{api.error && <button type="button" onClick={() => void api.reload()}>Повторить</button>}<button type="button" onClick={() => { setLocalError(null); api.clearError(); }}>Закрыть</button></div></div>}
    {api.loading ? <section className="ec-growth-loading"><span/><span/><span/></section> : api.reviews.length === 0 ? <section className="ec-growth-empty"><span className="ec-agent-office__mark"><SpecIcon/></span><h2>Добавьте первую спецификацию</h2><p>Утвердите eclipse.spec-gate.v1 в AI Hub и импортируйте JSON сюда для независимого решения команды.</p><button type="button" className="ec-btn ec-btn--primary" disabled={!canCreate} onClick={() => fileRef.current?.click()}>Импортировать JSON</button></section> : selected && <div className="ec-deck-workspace">
      <aside className="ec-deck-list"><div className="ec-growth-panel-head"><div><p className="ec-agent-office__section-label">Очередь</p><h2>Спецификации</h2></div><span>{api.reviews.length}</span></div>{api.reviews.map((item) => <Row key={item.id} item={item} selected={item.id === selected.id} onSelect={() => setSelectedId(item.id)}/>)}</aside>
      <section className="ec-deck-primary"><div className="ec-agent-office__objective"><div><p className="ec-agent-office__section-label">{selected.artifact.input.repository}</p><h2>{selected.artifact.input.projectName}</h2><p>{selected.artifact.input.problem}</p></div><span className="ec-agent-office__status" data-status={selected.reviewStatus}>{STATUS[selected.reviewStatus]}</span></div><dl className="ec-agent-office__guardrails"><div><dt>Результат</dt><dd>{selected.artifact.input.userOutcome}</dd></div><div><dt>Критерии</dt><dd>{selected.artifact.input.acceptanceCriteria.length}</dd></div><div><dt>Пути доказательств</dt><dd>{selected.artifact.verification.evidencePaths.length}</dd></div><div><dt>Реализация</dt><dd>Заблокирована</dd></div></dl>
        <div className="ec-deck-slides">{selected.artifact.stages.map((stage, index) => <article key={stage.id}><header><span>{index + 1}</span><div><small>{stage.command}</small><h3>{stage.id}</h3></div></header><p>{stage.summary}</p></article>)}</div>
        <section className="ec-growth-evidence"><div className="ec-growth-panel-head"><div><p className="ec-agent-office__section-label">В объёме</p><h2>Что делаем</h2></div><span>{selected.artifact.input.inScope.length} пунктов</span></div><ul>{selected.artifact.input.inScope.map((item) => <li key={item}><span>{item}</span></li>)}</ul><div className="ec-growth-panel-head"><div><p className="ec-agent-office__section-label">Вне объёма</p><h2>Что не делаем</h2></div></div><ul>{selected.artifact.input.outOfScope.map((item) => <li key={item}><span>{item}</span></li>)}</ul></section>
        <section className="ec-growth-artifacts"><div className="ec-growth-panel-head"><div><p className="ec-agent-office__section-label">Приёмка</p><h2>Проверяемые критерии</h2></div><span>{selected.artifact.tasks.length}</span></div>{selected.artifact.tasks.map((task) => <details key={task.id} open><summary><span>{task.id}</span><strong>{task.title}</strong></summary><div>{task.acceptanceCriterion}</div></details>)}</section>
      </section>
      <aside className="ec-deck-review"><section data-status={selected.reviewStatus}><p className="ec-agent-office__section-label">Ручное решение · v{selected.version}</p><h2>{STATUS[selected.reviewStatus]}</h2>{selected.reviewStatus === "PENDING" ? canReview ? <><p>Решение подтверждает только качество спецификации. Реализация остаётся отдельным действием.</p>{([['scopeConfirmed','Объём и исключения точны'],['risksConfirmed','Риски и ограничения понятны'],['rollbackConfirmed','Откат безопасен']] as const).map(([key,label]) => <label key={key}><input type="checkbox" checked={checklist[key]} onChange={(event) => setChecklist({ ...checklist, [key]: event.target.checked })}/><span>{label}</span></label>)}<textarea value={note} maxLength={1000} placeholder="Комментарий или причина доработки" onChange={(event) => setNote(event.target.value)}/><div><button type="button" className="ec-btn ec-btn--primary" disabled={!allChecked || api.reviewingId === selected.id} onClick={() => void decide("APPROVE")}>Принять спецификацию</button><button type="button" className="ec-btn ec-btn--danger" disabled={note.trim().length < 3 || api.reviewingId === selected.id} onClick={() => void decide("REJECT")}>Вернуть на доработку</button></div></> : <p>Решение принимает участник с правом согласования.</p> : <><p>{selected.reviewStatus === "APPROVED" ? "Спецификация готова к отдельному этапу реализации." : "Ожидается новая версия из AI Hub."}</p>{selected.reviewNote && <blockquote>{selected.reviewNote}</blockquote>}</>}</section><section><p className="ec-agent-office__section-label">План отката</p><p>{selected.artifact.input.rollbackPlan}</p></section><section><p className="ec-agent-office__section-label">Происхождение</p><dl className="ec-growth-provenance"><div><dt>Импортировал</dt><dd>{selected.importedBy?.displayName ?? "Удалённый участник"}</dd></div><div><dt>Исходная спецификация</dt><dd title={selected.sourceSpecId}>{selected.sourceSpecId}</dd></div><div><dt>Контракт</dt><dd>{selected.schemaVersion}</dd></div><div><dt>Импорт</dt><dd>{formatDate(selected.createdAt)}</dd></div></dl></section></aside>
    </div>}
  </main>;
}
