import { useCallback, useEffect, useState } from "react";
import { apiJson } from "../lib/api";

export type AuditReview = { id: string; sourceAuditId: string; schemaVersion: "eclipse.automation-audit.v1"; reviewStatus: "PENDING" | "APPROVED" | "REJECTED"; reviewNote: string | null; version: number; createdAt: string; artifact: { input: { businessName: string; objective: string; processName: string; proposal: { outcome: string; scope: string[]; exclusions: string[]; pilotMetric: string }; validation: { problem: string; audience: string; offer: string; interviews: number; waitlist: number; pilotEvidence: string } }; processMap: Array<{ order: number; step: string; system: string | null }>; claimAudit: Array<{ claim: string; status: "verified" | "qualified" | "remove"; reason: string }> }; receipt: null | { receiptId: string; issuedAt: string; statement: string } };

export function useAutomationAuditReviews(serverId: string) {
  const [reviews, setReviews] = useState<AuditReview[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { setLoading(true); if (!serverId) { setReviews([]); setLoading(false); return; } try { const data = await apiJson<{ reviews: AuditReview[] }>(`/api/servers/${encodeURIComponent(serverId)}/automation-audit-reviews`); setReviews(data.reviews); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить аудиты"); } finally { setLoading(false); } }, [serverId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const importArtifact = async (artifact: unknown) => { setBusy(true); try { const sourceId = typeof artifact === "object" && artifact && "id" in artifact ? String((artifact as { id: unknown }).id) : "unknown"; const data = await apiJson<{ review: AuditReview }>(`/api/servers/${encodeURIComponent(serverId)}/automation-audit-reviews/import`, { method: "POST", headers: { "Idempotency-Key": `automation-audit:${sourceId}`.slice(0, 128) }, body: JSON.stringify({ artifact }) }); setReviews((current) => [data.review, ...current.filter((item) => item.id !== data.review.id)]); setError(""); return data.review; } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось импортировать аудит"); return null; } finally { setBusy(false); } };
  const decide = async (review: AuditReview, decision: "APPROVE" | "REJECT", note: string, checks: { scopeConfirmed: boolean; claimsConfirmed: boolean; noExternalActionsConfirmed: boolean }) => { setBusy(true); try { const data = await apiJson<{ review: AuditReview }>(`/api/servers/${encodeURIComponent(serverId)}/automation-audit-reviews/${encodeURIComponent(review.id)}`, { method: "PATCH", body: JSON.stringify({ version: review.version, decision, note: note.trim() || undefined, ...checks }) }); setReviews((current) => current.map((item) => item.id === data.review.id ? data.review : item)); setError(""); return data.review; } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось сохранить решение"); return null; } finally { setBusy(false); } };
  return { reviews, loading, error, busy, importArtifact, decide };
}
