import { describe, expect, it } from "vitest";
import { parseAutomationAuditImport } from "./automationAuditContract.js";

const artifact = () => ({ schemaVersion: "eclipse.automation-audit.v1", id: "audit-1", status: "approved", createdAt: "2026-08-20T10:00:00.000Z", updatedAt: "2026-08-20T11:00:00.000Z",
  input: { businessName: "Demo", contactRole: "Owner", objective: "Reduce repeated proposal work.", processName: "Lead intake", processSteps: ["Receive lead", "Prepare proposal"], systems: ["CRM"], constraints: ["Read only"], evidence: [{ id: "EV-1", description: "Five reviewed interview notes", source: "Anonymized notes" }], proposal: { outcome: "Measure time on five leads", scope: ["Read-only map"], exclusions: ["No sending"], pilotMetric: "Minutes per lead" }, validation: { problem: "Repeated manual qualification work", audience: "Small B2B teams", offer: "Read-only audit", interviews: 5, waitlist: 0, pilotEvidence: "Five anonymized interviews" }, claims: [{ claim: "Five interviews were reviewed", evidenceIds: ["EV-1"] }] },
  processMap: [{ order: 1, step: "Receive lead", system: "CRM", access: "read_only" }, { order: 2, step: "Prepare proposal", system: null, access: "read_only" }], claimAudit: [{ claim: "Five interviews were reviewed", status: "verified", evidenceIds: ["EV-1"], reason: "Bound to evidence for human review" }], policy: { externalActions: false, oauthConnected: false, productionChanges: false, paymentsAllowed: false, readOnly: true }, approval: { scopeConfirmed: true, claimsConfirmed: true, noExternalActionsConfirmed: true, approvedAt: "2026-08-20T11:00:00.000Z" }, receipt: { receiptId: "receipt-audit-1", decision: "approved", issuedAt: "2026-08-20T11:00:00.000Z", statement: "Approved read-only proposal; no external action was performed." } });
describe("automation audit contract", () => {
  it("resets source approval and receipt on import", () => { const parsed = parseAutomationAuditImport(artifact()); expect(parsed.artifact.status).toBe("ready_for_review"); expect(parsed.artifact.approval).toBeNull(); expect(parsed.artifact.receipt).toBeNull(); });
  it("rejects evidence drift and secret-shaped content", () => { expect(() => parseAutomationAuditImport({ ...artifact(), input: { ...artifact().input, claims: [{ claim: "Unknown", evidenceIds: ["EV-404"] }] } })).toThrow(/Evidence/); expect(() => parseAutomationAuditImport({ ...artifact(), input: { ...artifact().input, objective: "token=super-secret-value-here" } })).toThrow(); });
});
